import { useEffect, useState } from 'react';
import Textarea from '@mui/joy/Textarea';
import Button from '@mui/material/Button';
import {
  setLocalStorage,
  getLocalStorage,
  createSummarizerSession,
  createPromptSession,
  sendContentMessage,
  getCurrentTab,
} from '../utils/utils.js';

const SingleNote = ({ setNotes, setShowNote }) => {
  const [questionName, setQuestionName] = useState('');

  const [isLoading, setIsLoading] = useState(true);
  // Summarized value of the question description
  const [questionSummary, setQuestionSummary] = useState('');
  // Question notes by the user
  const [questionNotes, setQuestionNotes] = useState('');
  // Tags generated by ai for the current question
  const [questionTags, setQuestionTags] = useState('');

  const generateQuestionDescription = async () => {
    try {
      // Getting current tab info
      const { url } = await getCurrentTab();

      // Checks if the URL is a valid leetcode question or not
      if (!url || !url.startsWith('https://leetcode.com/problems/')) {
        return;
      }
      // Updates the state with the leetcode question name
      setQuestionName(
        url.split('https://leetcode.com/problems/')[1]?.split('/')[0] ?? ''
      );

      // Gets the question description from contentScript.js
      const { questionDescription } = await sendContentMessage({
        type: 'getQuestionDescription',
      });

      const summarizeAI = await createSummarizerSession({
        sharedContext:
          'summarize the provided text in just one sentence, keep it short, easy to read and also gives the user a glimpse what the question is about.',
        type: 'tl;dr',
        format: 'plain-text',
        length: 'short',
      });

      const promptAI = await createPromptSession({
        systemPrompt: `Based on the provided LeetCode question, generate the tags in the a single string format like this: "tag1, tag2,.."
          •	The tags should be directly relevant to the question and reflect the core data structure and algorithm topics it involves.
          •	Assign a maximum of 2 tags to each question, ensuring they are highly specific to the question's requirements.
          •	Avoid generalized or non-DSA-specific tags like 'mathematics' or 'general problem-solving'.
          •	Focus on tags which correspond to well-known DSA concepts.
  
        Ensure the tags represent the primary techniques or concepts required to solve the question effectively`,
      });

      const tagsResp = await promptAI.prompt(
        `Question name is : ${questionName} and the question description is ${questionDescription}. Based on the information generate the maximum of 3 tags. If you can find the lesser most relevant tags that would be fine too.`
      );

      console.log(tagsResp); // TODO: for debugging

      const summary = await summarizeAI.summarize(questionDescription);

      setQuestionSummary(summary);

      setQuestionTags(tagsResp);

      setIsLoading(false);
    } catch (error) {
      console.log(
        'Error in SingleNote.jsx - generateQuestionDescription is:',
        error
      );
      setIsLoading(false);
    }
  };

  // Saves note in the local storage
  const saveNote = async () => {
    try {
      const newNote = {
        questionName: questionName,
        descripton: questionSummary,
        userNote: questionNotes,
        tags: questionTags?.split(','),
      };

      const storedNotes = await getLocalStorage({ param: 'notes' });

      // Check if `storedNotes` exists and has a `notes` array
      const existingNotes = storedNotes?.notes || [];

      // Update the existing note or add a new one
      const updatedNotes = existingNotes.some(
        (note) => note.questionName === questionName
      )
        ? existingNotes.map((note) =>
            note.questionName === questionName ? { ...note, ...newNote } : note
          )
        : [newNote, ...existingNotes];

      // Save the updated notes back to local storage
      setLocalStorage({ notes: updatedNotes });
      setNotes(updatedNotes);
      setShowNote(false);
    } catch (error) {
      console.log('Failed to store the note in the local storage: ', error);
      setShowNote(false);
    }
  };

  useEffect(() => {
    generateQuestionDescription();
  }, []);

  return (
    <>
      {questionName ? (
        <div className="flex flex-col p-2 border border-gray-600/45 rounded-lg gap-2 bg-[#1a1a2ba4]">
          <Textarea
            defaultValue={questionName}
            placeholder={'Question name'}
            sx={{
              backgroundColor: 'black',
              color: 'white',
              fontSize: '1rem',
              fontFamily: 'Inter',
              padding: '8px',
            }}
          />
          <Textarea
            placeholder={'Question summary'}
            value={isLoading ? 'Generating....' : questionSummary}
            disabled={isLoading}
            sx={{
              backgroundColor: 'black',
              color: 'white',
              fontSize: '1rem',
              fontFamily: 'Inter',
              padding: '8px',
            }}
            onChange={(e) => {
              setQuestionSummary(e.target?.value);
            }}
          />
          <Textarea
            placeholder={'Question notes'}
            maxRows={9}
            value={questionNotes}
            onChange={(e) => setQuestionNotes(e.target?.value)}
            sx={{
              backgroundColor: 'black',
              color: 'white',
              fontSize: '1rem',
              fontFamily: 'Inter',
              padding: '8px',
            }}
          />
          <Textarea
            placeholder={'Question tags'}
            minRows={0}
            maxRows={4}
            value={isLoading ? 'Generating...' : questionTags}
            onChange={(e) => {
              setQuestionTags(e.target?.value);
            }}
            disabled={isLoading}
            sx={{
              backgroundColor: 'black',
              color: 'white',
              fontSize: '1rem',
              fontFamily: 'Inter',
              padding: '8px',
            }}
          />
          <Button
            disabled={isLoading}
            className="cursor-pointer p-1 font-semibold"
            onClick={saveNote}
          >
            Submit
          </Button>
        </div>
      ) : null}
    </>
  );
};

export default SingleNote;
